spring:
  datasource:
    url: jdbc:mysql://190.15.198.27:15000/franquicia?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    open-in-view: true
    hibernate:
      ddl-auto: update
      jdbc:
          time_zone: UTC

  devtools:
    livereload:
      enabled: true
    add-properties: true
    
server:
  port: 7071

logging:
  level:
    web: debug
    org:
      hibernate:
        SQL: debug

cron:
      expression: "*/5 * * * * *"
loggin:
  user: "nahue_marcos"
  pass: "Nahue_Marcos"
  url: "http://10.101.102.1:8080"
  urlreporte: "http://127.0.0.1:7070"

consulta:
  accion: "consulta"
  uuid: "20c1bca6-ad60-48bf-bb34-b56115f527ef"
